# total of 1.5 CPUs e 3.0GB
version: "3.5"
name: scala-brawler
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=brawler
      - POSTGRES_USER=brawler
      - POSTGRES_DB=brawler
    ports:
      - "5432:5432"
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    # borrowed 😀
    command: 'postgres -c max_connections=200 -c shared_buffers=256MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U dev']
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '1GB'

  api01:
    image: scala-brawl:http4s-jvm-scala_2.13_latest
    pull_policy: if_not_present
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=8888
      - DB_HOST=db
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "960MB"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/health"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  api02:
    image: scala-brawl:http4s-jvm-scala_2.13_latest
    pull_policy: if_not_present
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=8887
      - DB_HOST=db
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "960MB"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/health"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '128MB'