# total of 1.5 CPUs e 3.0GB
version: "3.5"
name: scala-brawler
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=brawler
      - POSTGRES_USER=brawler
      - POSTGRES_DB=brawler
    ports:
      - "5432:5432"
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U dev']
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '1408MB'

  api01: &api
    image: educhaos/scala-brawl:http4s-native-scala_2.13_0.1
    pull_policy: if_not_present
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=8888
      - DB_HOST=db
    # debug jvm
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "1024MB"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/health"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  api02:
    <<: *api
    environment:
      - APP_PORT=8887
      - DB_HOST=db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '128MB'