FROM eclipse-temurin:17-jre-jammy
ARG SCALA_VER=2.13
ENV SCALA_VER ${SCALA_VER}
ADD target/scala-${SCALA_VER}/app.jar .
ENTRYPOINT ["java", "-XX:MaxRAMPercentage=75", "-XX:+AlwaysPreTouch", "-Xms512m", "-jar", "/app.jar"]